---
- name: "Cloning bitcoin-chain branch {{ bitcoin_branch }}"
  git:
    repo: "{{ bitcoin_repo }}"
    dest: "{{ bitcoin_home }}/bitcoin"
    force: yes
    version: "{{ bitcoin_branch }}"
    single_branch: yes
  become: yes
  become_user: "{{ bitcoin_user_name }}"

- name: "Runing autogen.sh"
  ansible.builtin.command: ./autogen.sh
  become: yes
  become_user: "{{ bitcoin_user_name }}"
  args:
    chdir: "{{ bitcoin_home }}/bitcoin"

- name: "Runing configure"
  ansible.builtin.command: ./configure
  become: yes
  become_user: "{{ bitcoin_user_name }}"
  args:
    chdir: "{{ bitcoin_home }}/bitcoin"

- name: "Compiling bitcoind"
  make:
    chdir: "{{ bitcoin_home }}/bitcoin"
  become: yes
  become_user: "{{ bitcoin_user_name }}"

- name: "Creating symlink for bitcoind"
  file:
    src: "{{ bitcoin_home }}/bitcoin/src/bitcoind"
    dest: "{{ bitcoin_home }}/bin/bitcoind"
    state: link
  become: true
  become_user: "{{ bitcoin_user_name }}"

- name: "Creating symlink for bitcoin-cli"
  file:
    src: "{{ bitcoin_home }}/bitcoin/src/bitcoin-cli"
    dest: "{{ bitcoin_home }}/bin/bitcoin-cli"
    state: link
  become: true
  become_user: "{{ bitcoin_user_name }}"

- name: "Creating bitcoin.conf"
  template:
    src: "bitcoin.conf.j2"
    dest: "{{ bitcoin_home }}/.bitcoin/bitcoin.conf"
    owner: "{{ bitcoin_user_name }}"
    group: "{{ bitcoin_user_name }}"
    mode: 0600
