---
- name: "Installing a List of Dependency Packages"
  apt:
    update_cache: yes
    pkg:
    - build-essential
    - libtool
    - autotools-dev
    - automake
    - pkg-config
    - bsdmainutils
    - python3
    - libevent-dev
    - libboost-dev  
    - libsqlite3-dev
    - sed
    - g++
    - make

- name: "Downloading the libdb"
  ansible.builtin.unarchive:
    src: "{{ libdb_url }}"
    dest: "{{ bitcoin_home }}"
    owner: "{{ bitcoin_user_name }}"
    group: "{{ bitcoin_user_name }}"
    #    mode: '0600'
    remote_src: yes

- name: "Changing the atomic.h"
  ansible.builtin.command: sed -i 's/__atomic_compare_exchange/__atomic_compare_exchange_db/g' dbinc/atomic.h
  become: yes
  become_user: "{{ bitcoin_user_name }}"
  args:
    chdir: "{{ bitcoin_home }}/db-{{ libdb_version }}"

- name: "Configuration libdb"
  ansible.builtin.command: ../dist/configure --prefix=/usr/local --enable-cxx
  become: yes
  become_user: "{{ bitcoin_user_name }}"
  args:
    chdir: "{{ bitcoin_home }}/db-{{ libdb_version }}/build_unix"

- name: "Compiling libdb"
  make:
    chdir: "{{ bitcoin_home }}/db-{{ libdb_version }}/build_unix"
  become: yes
  become_user: "{{ bitcoin_user_name }}"

- name: "Installing libdb"
  make:
    chdir: "{{ bitcoin_home }}/db-{{ libdb_version }}/build_unix"
    target: install
  become: yes

- name: "Setting environment variables {{ bitcoin_user_name }}"
  lineinfile:
    path: "/home/{{ bitcoin_user_name }}/.profile"
    line: "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib"
