---
- name: "Creating {{ bitcoin_user_name }} user"
  user:
    name: "{{ bitcoin_user_name }}"
    createhome: yes
    home: "/home/{{ bitcoin_user_name }}"
    shell: /bin/bash
    system: yes

- name: "Ensure {{ bitcoin_user_name }} user is part of systemd-journal group"
  user:
    name: "{{ bitcoin_user_name }}"
    groups: systemd-journal
    append: true
